# Generated by Django 5.2.3 on 2025-07-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
