# Generated by Django 5.2.4 on 2025-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_city_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address of the patient', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (drugs, food, environmental)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Patient's blood group", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications being taken', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Patient's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Previous medical conditions, surgeries, allergies', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, help_text="Patient's occupation", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
