# Generated by Django 5.2.4 on 2025-08-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_address_customuser_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consultation_duration',
            field=models.IntegerField(default=15, help_text='Duration of each consultation in minutes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_patient',
            field=models.ForeignKey(blank=True, help_text='Patient currently being consulted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='being_consulted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_queue_position',
            field=models.IntegerField(default=0, help_text='Current position in consultation queue'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='doctor_type',
            field=models.CharField(choices=[('permanent', 'Permanent Doctor (Always Available)'), ('visiting', 'Visiting Doctor (Special Days Only)')], default='permanent', help_text='Type of doctor', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_consulting',
            field=models.BooleanField(default=False, help_text='Currently consulting a patient'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_queue_size',
            field=models.IntegerField(default=10, help_text='Maximum number of patients in queue'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visiting_days',
            field=models.JSONField(blank=True, default=list, help_text='Days of week when visiting doctor is available (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visiting_end_date',
            field=models.DateField(blank=True, help_text='End date for visiting doctor availability', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visiting_start_date',
            field=models.DateField(blank=True, help_text='Start date for visiting doctor availability', null=True),
        ),
    ]
