# Generated by Django 5.2.4 on 2025-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_consultation_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='visiting_end_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='visiting_start_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='visiting_day_times',
            field=models.JSONField(blank=True, default=dict, help_text="Time slots for each visiting day {day_number: {'start_time': 'HH:MM', 'end_time': 'HH:MM'}}"),
        ),
    ]
