# Generated by Django 5.2.4 on 2025-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_visiting_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Pharmacist's availability status"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pharmacy_address',
            field=models.TextField(blank=True, help_text='Pharmacy address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pharmacy_license',
            field=models.CharField(blank=True, help_text='Pharmacy license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pharmacy_name',
            field=models.CharField(blank=True, help_text='Name of the pharmacy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Working hours (e.g., 9:00 AM - 6:00 PM)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist')], default='patient', max_length=10),
        ),
    ]
