# Generated by Django 5.2.4 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_is_available_customuser_pharmacy_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital_assignment',
            field=models.CharField(blank=True, help_text='Assigned hospital or department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available_for_duty',
            field=models.BooleanField(default=True, help_text="Nurse's availability for duty"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nurse_experience_years',
            field=models.IntegerField(blank=True, help_text='Years of nursing experience', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nurse_license',
            field=models.CharField(blank=True, help_text='Nurse license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nurse_specialization',
            field=models.CharField(blank=True, help_text='Nursing specialization (e.g., ICU, Emergency, Pediatric)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nursing_qualification',
            field=models.CharField(blank=True, help_text='Nursing qualification (e.g., BSc Nursing, GNM)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shift_preference',
            field=models.CharField(blank=True, help_text='Preferred shift (e.g., Day, Night, Rotating)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse')], default='patient', max_length=10),
        ),
    ]
