# Generated by Django 5.2.3 on 2025-06-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
