# Generated by Django 5.2.4 on 2025-08-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
    ]
