# Generated by Django 5.2.4 on 2025-08-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('queue', 'Queue Appointment (Permanent Doctor)'), ('scheduled', 'Scheduled Appointment (Visiting Doctor)')], default='scheduled', help_text='Type of appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_ended_at',
            field=models.DateTimeField(blank=True, help_text='When consultation ended', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, help_text='When consultation actually started', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_wait_time',
            field=models.IntegerField(blank=True, help_text='Estimated wait time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_queue_appointment',
            field=models.BooleanField(default=False, help_text='True if this is a queue-based appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_joined_at',
            field=models.DateTimeField(blank=True, help_text='When patient joined the queue', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.IntegerField(blank=True, help_text="Position in doctor's queue", null=True),
        ),
        migrations.CreateModel(
            name='DoctorQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_time', models.IntegerField(help_text='Estimated wait time in minutes')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('consulting', 'Consulting'), ('completed', 'Completed'), ('left', 'Left Queue')], default='waiting', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('doctor', 'patient', 'status')},
            },
        ),
        migrations.CreateModel(
            name='VisitingDoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
