# Generated by Django 5.2.4 on 2025-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorqueue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('consulting', 'Consulting'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('left', 'Left Queue')], default='waiting', max_length=20),
        ),
    ]
